version: "3"

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: sh -c "cd docs && bundle install && bundle exec jekyll serve --host 0.0.0.0 --watch --force_polling"
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll
    tty: true
